//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int stt { get; set; }
        public string Acount { get; set; }
        public string Company { get; set; }
        public string Bookie { get; set; }
        public string Bol { get; set; }
        public string Channel { get; set; }
        public string Rules { get; set; }
        public string State { get; set; }
    }
}
